### Logistic Regression Implementation

In [51]:
1+1

2

# Binary classification example

In [52]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
# %matplotlib inline

In [53]:
from sklearn.datasets import make_classification

In [54]:
X,y=make_classification(n_samples=10000,n_features=11,n_classes=2,random_state=42)

In [55]:
pd.DataFrame(X)

,0,1,2,3,4,5,6,7,8,9,10
0,-0.777562,1.245764,0.476016,0.306013,-1.080463,-0.660269,-1.457927,-0.525648,-1.143531,0.590277,-1.292743
1,0.495594,0.342306,0.922919,0.267236,-0.807758,-0.271053,0.660221,-0.037295,0.341214,-0.128445,-1.005734
2,-0.838054,0.850767,-0.730222,-0.115749,2.073883,-0.412116,-1.515254,0.636137,-1.064686,-1.017687,0.370479
3,0.722635,-1.173795,-2.496092,-1.209832,-0.143996,0.623389,-1.392451,-0.650036,1.068221,-0.345070,-1.345548
4,-0.437164,1.017015,-1.466707,-1.057299,-0.747328,-0.564002,-2.819337,0.291496,-0.750929,-1.267497,0.202908
...,...,...,...,...,...,...,...,...,...,...,...
9995,1.639431,1.112480,0.088286,0.460897,-0.024364,-0.884546,0.117968,1.458259,1.135521,0.692656,-1.623499
9996,-1.299674,-1.875767,-0.669054,0.174396,-0.307143,1.306367,1.462072,0.563298,-0.561163,0.144824,0.852501
9997,0.351549,0.964892,-1.321660,0.311916,0.224806,-0.631934,0.596821,-0.101256,-0.004286,-1.737611,0.597951
9998,-1.196007,0.928386,0.343975,0.608296,-0.159993,-0.414143,1.069189,0.896352,-1.421955,0.592726,-0.017270
9999,2.468058,1.779038,-2.354254,-1.135751,-0.737272,-1.395117,1.002534,1.527364,1.673883,-0.294406,-1.219474

In [56]:
pd.DataFrame(y)

      0
0     0
1     1
2     0
3     1
4     0
...  ..
9995  1
9996  0
9997  1
9998  0
9999  1

[10000 rows x 1 columns]

In [57]:
from sklearn.model_selection import train_test_split

In [58]:
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.25,random_state=42)

In [59]:
from sklearn.linear_model import LogisticRegression

In [60]:
Logistic=LogisticRegression()

In [61]:
Logistic.fit(X_train,y_train)

LogisticRegression()

In [62]:
y_pred=Logistic.predict(X_test)
print(y_pred)

[1 0 1 ... 1 1 0]

In [63]:
y_pred_prob=Logistic.predict_proba(X_test)
print(y_pred_prob)

[[0.40794927 0.59205073]
 [0.8139148  0.1860852 ]
 [0.06022771 0.93977229]
 ...
 [0.4983349  0.5016651 ]
 [0.46820558 0.53179442]
 [0.99664596 0.00335404]]

In [64]:
from sklearn.metrics import accuracy_score,confusion_matrix,classification_report
accuracy_score=accuracy_score(y_test,y_pred)
print("Accuracy Score:",accuracy_score)
confusion_matrix=confusion_matrix(y_test,y_pred)
print("Confusion Matrix:\n",confusion_matrix)
classification_report=classification_report(y_test,y_pred)
print("Classification Report:\n",classification_report)

Accuracy Score: 0.8972
Confusion Matrix:
 [[1138  122]
 [ 135 1105]]
Classification Report:
               precision    recall  f1-score   support

           0       0.89      0.90      0.90      1260
           1       0.90      0.89      0.90      1240

    accuracy                           0.90      2500
   macro avg       0.90      0.90      0.90      2500
weighted avg       0.90      0.90      0.90      2500

#### Hyperparameter Tuning and Cross Validation

In [71]:
model=LogisticRegression()
penalty=['l1', 'l2', 'elasticnet']
c_val=[0.01,0.1,1,10,100]
solver=['lbfgs', 'liblinear', 'newton-cg', 'newton-cholesky', 'sag', 'saga']

params=dict(penalty=penalty,C=c_val,solver=solver)

In [81]:
from sklearn.model_selection import GridSearchCV
from sklearn.model_selection import StratifiedKFold
cv=StratifiedKFold()

In [82]:
Grid=GridSearchCV(estimator=model,param_grid=params,cv=cv,n_jobs=-1,verbose=1)

In [83]:
Grid

GridSearchCV(cv=StratifiedKFold(n_splits=5, random_state=None, shuffle=False),
             estimator=LogisticRegression(), n_jobs=-1,
             param_grid={'C': [0.01, 0.1, 1, 10, 100],
                         'penalty': ['l1', 'l2', 'elasticnet'],
                         'solver': ['lbfgs', 'liblinear', 'newton-cg',
                                    'newton-cholesky', 'sag', 'saga']},
             verbose=1)

In [84]:
Grid.fit(X_train,y_train)

Fitting 5 folds for each of 90 candidates, totalling 450 fits

f:\anaconda3\envs\venv\Lib\site-packages\sklearn\model_selection\_validation.py:490: FitFailedWarning:
225 fits failed out of a total of 450.
The score on these train-test partitions for these parameters will be set to nan.
If these failures are not expected, you can try to debug them by setting error_score='raise'.

Below are more details about the failures:
--------------------------------------------------------------------------------
25 fits failed with the following error:
Traceback (most recent call last):
  File "f:\anaconda3\envs\venv\Lib\site-packages\sklearn\model_selection\_validation.py", line 833, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
  File "f:\anaconda3\envs\venv\Lib\site-packages\sklearn\base.py", line 1336, in wrapper
    return fit_method(estimator, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "f:\anaconda3\envs\venv\Lib\site-packages\sklearn\linear_model\_logistic.py", line 1147, in fit
    solver = _check_solver(self.solver, penalty, self.dual)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "f:\anaconda3\envs\venv\Lib\site-packages\sklearn\linear_model\_logistic.py", line 65, in _check_solver
    raise ValueError(
ValueError: Solver lbfgs supports only 'l2' or None penalties, got l1 penalty.

--------------------------------------------------------------------------------
25 fits failed with the following error:
Traceback (most recent call last):
  File "f:\anaconda3\envs\venv\Lib\site-packages\sklearn\model_selection\_validation.py", line 833, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
  File "f:\anaconda3\envs\venv\Lib\site-packages\sklearn\base.py", line 1336, in wrapper
    return fit_method(estimator, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "f:\anaconda3\envs\venv\Lib\site-packages\sklearn\linear_model\_logistic.py", line 1147, in fit
    solver = _check_solver(self.solver, penalty, self.dual)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "f:\anaconda3\envs\venv\Lib\site-packages\sklearn\linear_model\_logistic.py", line 65, in _check_solver
    raise ValueError(
ValueError: Solver newton-cg supports only 'l2' or None penalties, got l1 penalty.

--------------------------------------------------------------------------------
25 fits failed with the following error:
Traceback (most recent call last):
  File "f:\anaconda3\envs\venv\Lib\site-packages\sklearn\model_selection\_validation.py", line 833, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
  File "f:\anaconda3\envs\venv\Lib\site-packages\sklearn\base.py", line 1336, in wrapper
    return fit_method(estimator, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "f:\anaconda3\envs\venv\Lib\site-packages\sklearn\linear_model\_logistic.py", line 1147, in fit
    solver = _check_solver(self.solver, penalty, self.dual)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "f:\anaconda3\envs\venv\Lib\site-packages\sklearn\linear_model\_logistic.py", line 65, in _check_solver
    raise ValueError(
ValueError: Solver newton-cholesky supports only 'l2' or None penalties, got l1 penalty.

--------------------------------------------------------------------------------
25 fits failed with the following error:
Traceback (most recent call last):
  File "f:\anaconda3\envs\venv\Lib\site-packages\sklearn\model_selection\_validation.py", line 833, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
  File "f:\anaconda3\envs\venv\Lib\site-packages\sklearn\base.py", line 1336, in wrapper
    return fit_method(estimator, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "f:\anaconda3\envs\venv\Lib\site-packages\sklearn\linear_model\_logistic.py", line 1147, in fit
    solver = _check_solver(self.solver, penalty, self.dual)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "f:\anaconda3\envs\venv\Lib\site-packages\sklearn\linear_model\_logistic.py", line 65, in _check_solver
    raise ValueError(
ValueError: Solver sag supports only 'l2' or None penalties, got l1 penalty.

--------------------------------------------------------------------------------
25 fits failed with the following error:
Traceback (most recent call last):
  File "f:\anaconda3\envs\venv\Lib\site-packages\sklearn\model_selection\_validation.py", line 833, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
  File "f:\anaconda3\envs\venv\Lib\site-packages\sklearn\base.py", line 1336, in wrapper
    return fit_method(estimator, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "f:\anaconda3\envs\venv\Lib\site-packages\sklearn\linear_model\_logistic.py", line 1147, in fit
    solver = _check_solver(self.solver, penalty, self.dual)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "f:\anaconda3\envs\venv\Lib\site-packages\sklearn\linear_model\_logistic.py", line 65, in _check_solver
    raise ValueError(
ValueError: Solver lbfgs supports only 'l2' or None penalties, got elasticnet penalty.

--------------------------------------------------------------------------------
25 fits failed with the following error:
Traceback (most recent call last):
  File "f:\anaconda3\envs\venv\Lib\site-packages\sklearn\model_selection\_validation.py", line 833, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
  File "f:\anaconda3\envs\venv\Lib\site-packages\sklearn\base.py", line 1336, in wrapper
    return fit_method(estimator, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "f:\anaconda3\envs\venv\Lib\site-packages\sklearn\linear_model\_logistic.py", line 1147, in fit
    solver = _check_solver(self.solver, penalty, self.dual)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "f:\anaconda3\envs\venv\Lib\site-packages\sklearn\linear_model\_logistic.py", line 73, in _check_solver
    raise ValueError(
ValueError: Only 'saga' solver supports elasticnet penalty, got solver=liblinear.

--------------------------------------------------------------------------------
25 fits failed with the following error:
Traceback (most recent call last):
  File "f:\anaconda3\envs\venv\Lib\site-packages\sklearn\model_selection\_validation.py", line 833, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
  File "f:\anaconda3\envs\venv\Lib\site-packages\sklearn\base.py", line 1336, in wrapper
    return fit_method(estimator, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "f:\anaconda3\envs\venv\Lib\site-packages\sklearn\linear_model\_logistic.py", line 1147, in fit
    solver = _check_solver(self.solver, penalty, self.dual)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "f:\anaconda3\envs\venv\Lib\site-packages\sklearn\linear_model\_logistic.py", line 65, in _check_solver
    raise ValueError(
ValueError: Solver newton-cg supports only 'l2' or None penalties, got elasticnet penalty.

--------------------------------------------------------------------------------
25 fits failed with the following error:
Traceback (most recent call last):
  File "f:\anaconda3\envs\venv\Lib\site-packages\sklearn\model_selection\_validation.py", line 833, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
  File "f:\anaconda3\envs\venv\Lib\site-packages\sklearn\base.py", line 1336, in wrapper
    return fit_method(estimator, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "f:\anaconda3\envs\venv\Lib\site-packages\sklearn\linear_model\_logistic.py", line 1147, in fit
    solver = _check_solver(self.solver, penalty, self.dual)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "f:\anaconda3\envs\venv\Lib\site-packages\sklearn\linear_model\_logistic.py", line 65, in _check_solver
    raise ValueError(
ValueError: Solver newton-cholesky supports only 'l2' or None penalties, got elasticnet penalty.

--------------------------------------------------------------------------------
25 fits failed with the following error:
Traceback (most recent call last):
  File "f:\anaconda3\envs\venv\Lib\site-packages\sklearn\model_selection\_validation.py", line 833, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
  File "f:\anaconda3\envs\venv\Lib\site-packages\sklearn\base.py", line 1336, in wrapper
    return fit_method(estimator, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "f:\anaconda3\envs\venv\Lib\site-packages\sklearn\linear_model\_logistic.py", line 1147, in fit
    solver = _check_solver(self.solver, penalty, self.dual)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "f:\anaconda3\envs\venv\Lib\site-packages\sklearn\linear_model\_logistic.py", line 65, in _check_solver
    raise ValueError(
ValueError: Solver sag supports only 'l2' or None penalties, got elasticnet penalty.

  warnings.warn(some_fits_failed_message, FitFailedWarning)
f:\anaconda3\envs\venv\Lib\site-packages\sklearn\model_selection\_search.py:1137: UserWarning: One or more of the test scores are non-finite: [       nan 0.89026667        nan        nan        nan 0.88946667
 0.8888     0.88893333 0.8888     0.8888     0.88866667 0.8888
        nan        nan        nan        nan        nan 0.8888
        nan 0.88653333        nan        nan        nan 0.88613333
 0.88613333 0.88613333 0.88613333 0.88613333 0.88613333 0.88613333
        nan        nan        nan        nan        nan 0.88613333
        nan 0.8848            nan        nan        nan 0.88493333
 0.8852     0.8852     0.8852     0.8852     0.8852     0.8852
        nan        nan        nan        nan        nan 0.8852
        nan 0.88493333        nan        nan        nan 0.88493333
 0.88493333 0.88493333 0.88493333 0.88493333 0.88493333 0.88493333
        nan        nan        nan        nan        nan 0.88493333
        nan 0.88493333        nan        nan        nan 0.88493333
 0.88493333 0.88493333 0.88493333 0.88493333 0.88493333 0.88493333
        nan        nan        nan        nan        nan 0.88493333]
  warnings.warn(
f:\anaconda3\envs\venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1135: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', and C=np.inf instead of penalty=None.
  warnings.warn(
f:\anaconda3\envs\venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1160: UserWarning: Inconsistent values: penalty=l1 with l1_ratio=0.0. penalty is deprecated. Please use l1_ratio only.
  warnings.warn(

GridSearchCV(cv=StratifiedKFold(n_splits=5, random_state=None, shuffle=False),
             estimator=LogisticRegression(), n_jobs=-1,
             param_grid={'C': [0.01, 0.1, 1, 10, 100],
                         'penalty': ['l1', 'l2', 'elasticnet'],
                         'solver': ['lbfgs', 'liblinear', 'newton-cg',
                                    'newton-cholesky', 'sag', 'saga']},
             verbose=1)

In [85]:
Grid_best_params_=Grid.best_params_
print("Best Parameters:",Grid_best_params_)

Best Parameters: {'C': 0.01, 'penalty': 'l1', 'solver': 'liblinear'}

In [87]:
y_pred1=Grid.predict(X_test)

In [88]:
from sklearn.metrics import accuracy_score,confusion_matrix,classification_report
accuracy_score=accuracy_score(y_test,y_pred1)
print("Accuracy Score:",accuracy_score)
confusion_matrix=confusion_matrix(y_test,y_pred1)
print("Confusion Matrix:\n",confusion_matrix)
classification_report=classification_report(y_test,y_pred1)
print("Classification Report:\n",classification_report)

Accuracy Score: 0.902
Confusion Matrix:
 [[1136  124]
 [ 121 1119]]
Classification Report:
               precision    recall  f1-score   support

           0       0.90      0.90      0.90      1260
           1       0.90      0.90      0.90      1240

    accuracy                           0.90      2500
   macro avg       0.90      0.90      0.90      2500
weighted avg       0.90      0.90      0.90      2500

### Randomized Search CV

In [89]:
from sklearn.model_selection import RandomizedSearchCV
from sklearn.model_selection import StratifiedKFold
cv=StratifiedKFold()

In [90]:
random=RandomizedSearchCV(estimator=model,param_distributions=params,cv=cv,n_jobs=-1,verbose=1,n_iter=10)

In [91]:
random

RandomizedSearchCV(cv=StratifiedKFold(n_splits=5, random_state=None, shuffle=False),
                   estimator=LogisticRegression(), n_jobs=-1,
                   param_distributions={'C': [0.01, 0.1, 1, 10, 100],
                                        'penalty': ['l1', 'l2', 'elasticnet'],
                                        'solver': ['lbfgs', 'liblinear',
                                                   'newton-cg',
                                                   'newton-cholesky', 'sag',
                                                   'saga']},
                   verbose=1)

In [92]:
random.fit(X_train,y_train)

Fitting 5 folds for each of 10 candidates, totalling 50 fits

f:\anaconda3\envs\venv\Lib\site-packages\sklearn\model_selection\_validation.py:490: FitFailedWarning:
25 fits failed out of a total of 50.
The score on these train-test partitions for these parameters will be set to nan.
If these failures are not expected, you can try to debug them by setting error_score='raise'.

Below are more details about the failures:
--------------------------------------------------------------------------------
10 fits failed with the following error:
Traceback (most recent call last):
  File "f:\anaconda3\envs\venv\Lib\site-packages\sklearn\model_selection\_validation.py", line 833, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
  File "f:\anaconda3\envs\venv\Lib\site-packages\sklearn\base.py", line 1336, in wrapper
    return fit_method(estimator, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "f:\anaconda3\envs\venv\Lib\site-packages\sklearn\linear_model\_logistic.py", line 1147, in fit
    solver = _check_solver(self.solver, penalty, self.dual)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "f:\anaconda3\envs\venv\Lib\site-packages\sklearn\linear_model\_logistic.py", line 65, in _check_solver
    raise ValueError(
ValueError: Solver lbfgs supports only 'l2' or None penalties, got l1 penalty.

--------------------------------------------------------------------------------
5 fits failed with the following error:
Traceback (most recent call last):
  File "f:\anaconda3\envs\venv\Lib\site-packages\sklearn\model_selection\_validation.py", line 833, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
  File "f:\anaconda3\envs\venv\Lib\site-packages\sklearn\base.py", line 1336, in wrapper
    return fit_method(estimator, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "f:\anaconda3\envs\venv\Lib\site-packages\sklearn\linear_model\_logistic.py", line 1147, in fit
    solver = _check_solver(self.solver, penalty, self.dual)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "f:\anaconda3\envs\venv\Lib\site-packages\sklearn\linear_model\_logistic.py", line 65, in _check_solver
    raise ValueError(
ValueError: Solver sag supports only 'l2' or None penalties, got elasticnet penalty.

--------------------------------------------------------------------------------
10 fits failed with the following error:
Traceback (most recent call last):
  File "f:\anaconda3\envs\venv\Lib\site-packages\sklearn\model_selection\_validation.py", line 833, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
  File "f:\anaconda3\envs\venv\Lib\site-packages\sklearn\base.py", line 1336, in wrapper
    return fit_method(estimator, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "f:\anaconda3\envs\venv\Lib\site-packages\sklearn\linear_model\_logistic.py", line 1147, in fit
    solver = _check_solver(self.solver, penalty, self.dual)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "f:\anaconda3\envs\venv\Lib\site-packages\sklearn\linear_model\_logistic.py", line 73, in _check_solver
    raise ValueError(
ValueError: Only 'saga' solver supports elasticnet penalty, got solver=liblinear.

  warnings.warn(some_fits_failed_message, FitFailedWarning)
f:\anaconda3\envs\venv\Lib\site-packages\sklearn\model_selection\_search.py:1137: UserWarning: One or more of the test scores are non-finite: [0.88493333 0.8852     0.88946667 0.8888            nan        nan
 0.88493333        nan        nan        nan]
  warnings.warn(
f:\anaconda3\envs\venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1135: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', and C=np.inf instead of penalty=None.
  warnings.warn(
f:\anaconda3\envs\venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1160: UserWarning: Inconsistent values: penalty=l1 with l1_ratio=0.0. penalty is deprecated. Please use l1_ratio only.
  warnings.warn(

RandomizedSearchCV(cv=StratifiedKFold(n_splits=5, random_state=None, shuffle=False),
                   estimator=LogisticRegression(), n_jobs=-1,
                   param_distributions={'C': [0.01, 0.1, 1, 10, 100],
                                        'penalty': ['l1', 'l2', 'elasticnet'],
                                        'solver': ['lbfgs', 'liblinear',
                                                   'newton-cg',
                                                   'newton-cholesky', 'sag',
                                                   'saga']},
                   verbose=1)

In [93]:
random_best_params_=random.best_params_
print("Best Parameters from Randomized Search:",random_best_params_)

Best Parameters from Randomized Search: {'solver': 'saga', 'penalty': 'l1', 'C': 0.01}

In [94]:
y_pred=random.predict(X_test)

In [95]:
from sklearn.metrics import accuracy_score,confusion_matrix,classification_report
accuracy_score=accuracy_score(y_test,y_pred)
print("Accuracy Score:",accuracy_score)
confusion_matrix=confusion_matrix(y_test,y_pred)
print("Confusion Matrix:\n",confusion_matrix)
classification_report=classification_report(y_test,y_pred)
print("Classification Report:\n",classification_report)

Accuracy Score: 0.9
Confusion Matrix:
 [[1141  119]
 [ 131 1109]]
Classification Report:
               precision    recall  f1-score   support

           0       0.90      0.91      0.90      1260
           1       0.90      0.89      0.90      1240

    accuracy                           0.90      2500
   macro avg       0.90      0.90      0.90      2500
weighted avg       0.90      0.90      0.90      2500

ValueError: All arrays must be of the same length